name: Code Coverage Report
description: Comments a pull request with the code coverage
author: Romeo Van Snick
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  reports-array:
    description: The location of the lcov.info file
    required: false
  base-reports-array:
    description: The location of the lcov file for the base branch
    required: false
  working-directory:
    description: Sub-directory to get reports from
    required: false
runs:
  using: node12
  main: dist/main.js
